icenet-ai/icenet

icenet/model/models.py
Looking to fix #87. Just replacing the problematic `np.int()`s with `int()`s which is what numpy recommends to do in the error.
`np.int()` only seems to occur in `icenet/model/models.py`.
=> replace `np.int()` with `int()`

icenet/plotting/forecast.py, setup.py
Partly working through #95 and #93.
This PR will close #108 too.
To do:
**MAE, MSE, RMSE metric plots**
```
icenet_plot_metrics north preds.nc 2016-03-31 -m MSE,MAE,RMSE
```
creates the following plot
(can choose which metrics to plot in the command, but by default plots them all).
Will work on implementing CLI for plotting SIE metric next...
=> CLI for plotting MAE,MSE,RMSE,SIE metrics for forecasts

icenet/plotting/forecast.py
Fix for #129 (`threshold` was not passed into `compute_sea_ice_extent_error` call when plotting SIE).
=> #129 fix: add threshold arg when plotting and computing SIE

icenet/model/predict.py
Fix for #133.
By default, when we're running predictions, we no longer save weights, inputs and raw outputs (which are useful for debugging). In particular, I introduce the `save_args` argument to `predict_forecast` and `run_prediction` functions. The CLI command for prediction, `icenet_predict`, has a new flag `-s` or `--save_args`. When called, it will save these outputs, but otherwise does not.
Will help alleviate some storage issues when predicting.
=> Fixes #133: Make it optional to save outputs for debugging when predicting

icenet/plotting/forecast.py
Fix for #135.
Sorts the metrics dataframe by the date (either month or day depending on what you're averaging over), and makes sure the labels are sorted so they point to the correct date.
=> Fixes #135: Sort values in dataframe for leadtime avg plots and labels

icenet/data/sic/osisaf.py
Dev #138, facilitates naive use of dask to spread the load when computing SIC data stores from OSI-SAF
=> Adding dask compute to the SIC downloading

icenet/data/cli.py, icenet/data/dataset.py, icenet/data/loaders/base.py, icenet/data/loaders/dask.py, icenet/data/sic/osisaf.py, icenet/model/train.py, icenet/plotting/data.py
Fixes #181:
- When initialising a dataloder from a dataset, it now has the same `n_forecast_days` as the dataset by default (so now passing a `n_forecast_days` argument in the IceNetDataSet.get_data_loader() method)
- I've also done this for the number of workers too as that is something that wasn't being recorded in the dataset config to recreate the dataloader
- Added `n_forecast_days` argument `to IceNetDataSet.get_data_loader()` to allow user to have a different `n_forecast_days` in the dataloader than that of the dataset
- Added `n_forecast_days` argument to `IceNetBaseDataLoader.generate_sample()` to allow user to specify a different `n_forecast_days` than what has been set when the dataloader was created.
There is also some other small fixes to other issues - these were needed to …
=> #181: Fix n_forecast_days consistency

icenet/data/processors/utils.py, icenet/model/train.py, icenet/plotting/data.py, icenet/plotting/forecast.py, icenet/plotting/utils.py
Fixes linting issues in #198, opted to ignore `E721 Do not compare types, use 'isinstance()'`.
May revisit later, but `type()` currently used for standard built-in types.
=> Fixes #198: Linting fixes

icenet/data/sic/osisaf.py
Fixes #192 by correcting start date for OSI SAF 430a dataset download.
=> Fixes #192: Issue running icenet_data_sic with 2020 date range

requirements.txt
Fixes #201 by unpinning older h5py version with newer Python versions. Newer h5py version required on newer Python versions.
Need to review, if still causing conflicts with Issue #62 - which might be due to a specific local/conda hdf5 library.
=> Fixes #201 tox environment set-up error.

icenet/data/loaders/dask.py
Allows serial reads into xarray dataset from netCDF files in `DaskMultiWorkerLoader` class when loading multiple files.
This allows PyTorch dataloader to use the existing `IceNetDataLoader` class to generate samples without causing intermitted & random file close errors (when `generate_samples()` is called with `parallel=False`).
Leave it as `True` by default for backwards compatibility.
=> Fixes #207: Make parallel read an optional arg

requirements.txt
Resolves #214 where v0.2.6 and earlier can have dependency issue with numpy in Python 3.8 by enforcing h5py to be newer than the version pinned till v0.2.7.
=> Resolves #214: h5py dependency error

icenet/data/sic/osisaf.py
Fixes issue #217, where already downloaded dates are not skipped.
Now, correctly identifies the number of dates that will be skipped since already downloaded. Before, would always say dates would be excluded, but not actually be excluded in processing.
Have verified through dumps and diffs of the merged netCDF file.
=> Fixes #217: OSI-SAF SIC already downloaded dates not skipped

icenet/data/sic/osisaf.py
Resolves #184 zero sic file issue by detecting small (<100 byte) files on OSI-SAF ftp server, and adding it to `invalid_dates` to process since they should be around 1MB.
=> Resolves #184 zero sic file issue

icenet/data/loaders/dask.py
Fixes #231 
Initialise `LocalCluster` using context manager so resources are released once compute is complete.
Else, currently, the workers are left running. Finding it to be a limiting issue with low memory systems.
=> Fixes #231 dask resource release

setup.py
Fixes #197, removes 3.7 from `setup.py`.
=> Fixes #197 Drop python 3.7

requirements.txt
Resolves #238 
Constrain Tensorflow version so Keras 2 is installed easily alongside it, since Keras>=3 requires saving models to `.keras` files instead of `.h5`
See corresponding issue for more details.
=> Fixes #238: Constrain Tensorflow version

README.md
Resolves #222 
Mention installation requirement of system eccodes library in addition to the python wrapper.
Also, mentions the `add-cuda` extra available when installing newer versions of Tensorflow that will install CUDA packages via pip for Nvidia GPU support.
```bash
pip install tensorflow[and-cuda]<2.16
```
=> Resolves #222: Mention installation of eccodes

.gitignore, icenet/data/dataset.py
Potentially fix the root logger being set to warning - where the first logging call (warning that PyTorch was not installed/loadable) would set the loglevel for the root logger and affect every log call.
=> Fix torch logging

icenet/data/dataset.py
Replaced the print statements with logger.
This pull request resolves - Update pytorch load fail from print to logging #251
=> Resolves - Update pytorch load fail from print to logging #251

icenet/data/dataset.py
Resolves #235 
Uses `.get` to set defaults for `generate_workers` to cover previous versions where this was not specfied in the `dataset_config.{name}.config` file.
=> Fixes #235 defensive generate workers

icenet/data/dataset.py, icenet/utils.py
Resolves #251 
Create a separate logger instance to prevent setting the root logger level before its configured in `setup_logging()` in `icenet/utils.py`.
Tested using:
```python
import logging
print("Root logging level: ", logging.getLogger().level)
import icenet.data.dataset
logging.basicConfig(level=logging.CRITICAL)
print("Root logging level: ", logging.getLogger().level)
```
=> Fixes #251 torch import logging

icenet/data/interfaces/cmems.py, icenet/exceptions.py
Fixes #270
This replaces MOTU client usage for downloading ORAS5 ocean data which is no longer in service as of [March 2024](https://marine.copernicus.eu/user-corner/user-notification-service/transition-marine-data-store).
Will not close the relating issue since this uses CLI approach for simpler tie-in with previous approach.
Would recommend moving to Copernicus marine toolbox Python API (very low prio), but easy transition.
metadata caching is disabled to avoid having to change the default caching directory, and prevent `LockException` error:
https://help.marine.copernicus.eu/en/articles/8632322-copernicus-marine-toolbox-troubleshoots#h_974e43dc00
=> Resolves #270 ORAS5Downloader downloader update

icenet/plotting/forecast.py
Resolves #277 
Updates `matplotlib.cm.get_cmap` to `matplotlib.pyplot.get_cmap` as per following API change to allow matplotlib >= 3.9.0 support.
https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.9.0.html#removals
=> Fixes #277: Matplotlib get_cmap method API deprecation 

icenet/plotting/forecast.py
Fixes #289 
Initial start date of ecmwf forecast now included
=> Fix #289: Include ecmwf start forecast date for compute_metrics_leadtime_avg

icenet/data/interfaces/cds.py
Resolves #299 
Fixes typo in variable being omitted when using ERA5Downloader with new CDSAPI. See above issue for more details.
Also, added a guard to raise an error if more than one variable is found for processing.
=> Fixes #299 - typo fix

icenet/data/interfaces/cds.py
Resolves #304 
This was an edge case, where if you have partial ERA5 data for the first day of the month, it will try to filter out the first day since there isn't 24 hours worth of data to create an average for the day. So, it tries to filter it out and since the result is nothing, it fails. See code comment for more detail.
```python
```
=> Fix #304: ERA5 Download error for first day of month

icenet/data/process.py
Resolves #303 
As per title, omits loading `lambert_azimuthal_equal_area` variable when loading multiple datasets in one go since in some cases, this variable is missing.
=> Fix #303: Omit lambert_azimuthal_equal_area var when loading nc file

requirements.txt
Resolves #309 
Sets minimum `eccodes` to version that should include binary requirement of `eccodes` along with the python module.
=> Fix #309: Set min eccodes version in requirements

icenet/plotting/video.py, requirements.txt
Resolves #316 
As per title, uses `imageio-ffmpeg` library which downloads ffmpeg binaries, and then, in IceNet point to it before saving matplotlib animation.
This allows removal of system/conda ffmpeg dependency.
=> Fix #316: Use imageio-ffmpeg ffmpeg binary for matplotlib mp4 output

requirements.txt
Temporary fix for eccodes requirements for v0.2.9 release.
Specify version range for eccodes since binary seems to be missing in newer versions `v2.39.0+`
=> Dev #318: Temporarily use version specification on eccodes to 2.37.0-2.38.3

environment.yml, icenet/data/process.py, icenet/data/sic/mask.py, icenet/plotting/__init__.py, icenet/plotting/forecast.py, icenet/plotting/utils.py, icenet/plotting/video.py
Resolves #279 and #100 
* Uses Cartopy to enable north-facing plots.
* Enable defining region for forecast output based on lat/lon bounds and not just pixel bounds.
* Enable gridlines optionally.
* Enable coastlines with mp4 animation output (Fixing #100).
There is still work to be done on using the lat/lon which will likely need some refactoring of the `Masks` class. When `process_regions` is called and `Masks` is provided to it here:
https://github.com/icenet-ai/icenet/blob/f1285368eb731ed473c6b574b1d48ae574a8c01e/icenet/plotting/forecast.py#L1486-L1488
It defines a pixel based slice which is set by `getitem` in the Masks class. (This is the case for all times `process_regions` is called in `forecast.py` above)
https://github.com/icenet-ai/icenet/blob/f1285368eb731ed473c6b574b1d48ae574a8 …
=> Fixes #279 and #100 plotting updates
